### ISSUE TITLE
https://github.com/f5devcentral/f5-velos-training/blob/dev/docs/postman/F5%20Postman%20for%20F5OS-C%20VELOS%20Environment.postman_environment.json

### ISSUE THREAD

**Issue by eos500n2000** [f5devcentral/f5-velos-training#2]
https://github.com/f5devcentral/f5-velos-training/blob/dev/docs/postman/F5%20Postman%20for%20F5OS-C%20VELOS%20Environment.postman_environment.json

json format error.

		{
			"key": "velos_license_registration_key_chassis2",
			"value": "XXXXX-XXXXX-XXXXX-XXXXX-XXXXXXX",
			"enabled": true
		},          ###### remove ","
	],

**Comment by jimmccarron** [comment]
Removed extra comma. Fixed
